//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTASK_7_28_2024_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPHONEINFO
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string IMAGE { get; set; }
    }
}
